[package]
name = "osrs-random"
version = "0.1.0"
edition = "2021"
authors = ["Connor Field <connor@connorfield.com>"]

[dependencies]
rand = "0.8"
clap = { version = "3.1", features = ["derive"] }
colored = "2.0"
prettytable-rs = "^0.10"
once_cell = "1.10.0"
crossterm = "0.24"
