[package]
name = "osrs-random"
version = "1.0.1"
edition = "2021"
authors = ["Connor Field <connor@connorfield.com>"]
description = "A random boss and skill generator for Old School RuneScape"
repository = "https://github.com/ConnorField/osrs-random"
license = "MIT"

[dependencies]
rand = "0.8.5"
clap = { version = "3.2", features = ["derive"] }
prettytable-rs = "^0.10"
once_cell = "1.18.0"
crossterm = "0.26.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
