[package]
name = "osrs-random"
version = "0.1.0"
edition = "2021"
authors = ["Connor Field <connor@connorfield.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
